language: node_js

sudo: false

node_js:
  - "7"
  - "6"
  - "5"

cache:
  directories:
    - node_modules

branches:
  only:
    - travis-ci

#install:
#- docker build -t blog .
- docker run -d -p 127.0.0.1:80:80 --name blog blog

before_script:
- npm install

script:
- npm build
- sh .travis/test.sh