language: node_js

sudo: false

node_js:
  - "7"
  - "6"
  - "5"

cache:
  apt: true
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  ssh_known_hosts: github.com

script:
  - 'npm run build'
  - 'npm run clean'
  - 'npm run deploy  "${TRAVIS_PULL_REQUEST}"'

branches:
  only:
    - v2

env:
  global:
    - CXX: g++-4.8
    - GH_REPO: "github.com/o2team/o2team.github.io.git"
    - secure: "H+LCehn5ve9wjaEYRsVCQa43dlvvWveTEOOrpSCu8XKW9Xbfnpp2ph1obsLhKnS3LHV4e9D5LzyWEAvcMV4r+QGB5dPfv6L4Ww6pUPhiJYreLU+SED2q0aO9lUiQXkE5siEHFbMB1XVUIcEetu41Uwe+lszS9olu5Ko+qId9DCoIgSkur6X1n7O1TH6hSWT5xz/djotzyh6abkZTCYBIIMK/D5o/XlxHggTrgIKt9hx6vMKUUHmQUkrhs5wvpQzMJB+QFjl+dFui6s2dVhpTSO4aweyeY+MJ4nzFOHDOY70gAtA0sMRZGWWV5icTSXUn2BGoeFTY1EzUYHhWtSMcEvHAgEPnrgOKGoq92+xZ27n30yr+ac2jZJQEvVPgeLMRwlVTUZhc3Z+UH4PxE0fkTd6M2t5b5mmhtRXK62e1x1IEOoOG3dJp2DzF0LNekuYM4UuLdt9K9/KSeaDoh/jg4MU7wH1Omd/v3qEHxFCaoKE1Nkqy0rp1zVfy1KnVw25mcdTcBcYhquRAsmwmtlZvxSl5cuCme7XGytmSgG74IewmG3pOo8EKwPoh62ehFSW2PLGyuyHmC8tvtDIFefrmMW1Je0cJt53KRCeGCcMmWydfz4qJlzxejADbzDtVVZFmzQRlIfUD3OnTFKvRdsdgMpZ9cRic69mP+I3ox5QbkdE="
Contact GitHub API Training Shop Blog About


install:
- docker build -t blog .
- docker run -d -p 127.0.0.1:80:80 --name blog blog

before_script:
- pip install -r requirements.txt
- pip install mock
- pip install requests
- pip install feedparser

script:
- docker ps | grep -q blog
- sh test.sh